services:
  litchi:
    build:
      context: .
      dockerfile: Dockerfile
      secrets:
        - grandlyon_user
        - grandlyon_pass
    ports:
      - 8000:8000
    env_file: ".env"
    restart: always

secrets:
  grandlyon_pass:
    environment: GRANDLYON_PASS
  grandlyon_user:
    environment: GRANDLYON_USER